### ISSUE TITLE
path.exists has been removed in newer versions of node

### ISSUE THREAD

**Issue by tnrich** [substack/npmdep#3]
```
npmdep requires fsevents
/Users/tnrich/.nvm/versions/node/v4.4.7/lib/node_modules/npmdep/index.js:15
    else path.exists(cacheFile, function (ex) {
              ^

TypeError: path.exists is not a function
    at Object.exports.load (/Users/tnrich/.nvm/versions/node/v4.4.7/lib/node_modules/npmdep/index.js:15:15)
    at Object.exports.requires (/Users/tnrich/.nvm/versions/node/v4.4.7/lib/node_modules/npmdep/index.js:27:13)
    at Object.<anonymous> (/Users/tnrich/.nvm/versions/node/v4.4.7/lib/node_modules/npmdep/cli.js:22:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by tnrich** [comment]
I believe it should now be `fs.exists`
